text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "webserver:/home/admin/sites/michaelbarton.me.uk/projects/scaffolder"
    options: [ '-gpPrvz' ]
site:
  title: "Scaffolder"
  subtitle: "Genome scaffolding for human beings"
  url: "http://www.michaelbarton.me.uk/projects/scaffolder"
  analytics_token: "UA-1362555-4"
  favicon: false
  navigation:
    'api documentation': "http://rubydoc.info/gems/scaffolder/frames"
    'unix manual pages': "/man"
    'contribute':        "/contribute"
author:
  url: "http://www.michaelbarton.me.uk"
  name: "Michael Barton"
google_fonts:
  Molengo:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
  Volkorn:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
  Nobile:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
scripts:
  - "https://www.google.com/jsapi?key=ABQIAAAAY-Po-vITSRs13yAER6R-vxSra3Sy8luTxRRrne7YP3mAkjpCARS9K_z0sLbKHzv2zlMNiYLq0UExIg"
  - "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  - "/vendor/fancybox/javascript.js"
  - "/javascript/prettify.js"
stylesheets:
  "/stylesheets/screen.css": "screen,projection"
  "/stylesheets/print.css": "print"
  "/vendor/fancybox/styles.css": "screen,projection"
